# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - initiative-uat
    exclude:
    - initiative-sit
    - master
  paths:
    include:
    - initiative.sso.web/* 
    exclude:
    - initiative.sso.api/* 
    - initiative.sso.db/* 
    - initiative.sso.models/* 
    - initiative.sso.api.tests/* 
    
pool:
  vmImage: 'ubuntu-latest'



steps:

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install Angular-CLI'

- task: Npm@1
  inputs:
    workingDir: initiative.sso.web
    verbose: false
  displayName: 'Restore Dependencies'

- task: Npm@1
  inputs:
    command: custom
    workingDir: initiative.sso.web
    verbose: false
    customCommand: 'run build'
  displayName: 'Build Angular'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: initiative.sso.web
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
      
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'